function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * A placement generated by the Attivio Business Center
 * that you can display along with search results.
 */
var SearchPlacement = function () {
  function SearchPlacement() {
    _classCallCheck(this, SearchPlacement);
  }

  SearchPlacement.fromJson = function fromJson(json) {
    var result = new SearchPlacement();
    result.label = json.label;
    result.imageUrl = json.imageUrl;
    result.linkText = json.linkText;
    result.linkUrl = json.linkUrl;
    result.markup = json.markup;
    return result;
  };

  /** The label to display */

  /** The URL of an image to display */

  /** The text to display for a hyperlink */

  /** The URL that should be the target of the hyperlink */

  /** HTML markup for the placement to be displayed as-is */


  return SearchPlacement;
}();

export { SearchPlacement as default };